#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Arash Sajjadi
"""v3.15.0 QA: derive the FULL model inventory + capability truth from source.

Iterates the registry, calls ``model_capabilities()`` for every model (which in
turn reads the licensing policy, _TRAINING_TABLE, _EXPORT_TABLE, and the engine
registry), and writes:

    docs/qa/v315_model_coverage/model_inventory.json
    docs/qa/v315_model_coverage/model_inventory.md
    docs/qa/v315_model_coverage/model_truth_table.md

Nothing here relies on memory — it is derived entirely from the registry/policy/
tables/engine-registry in source.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path


def build_rows() -> list[dict]:
    from visionservex.core.model import model_capabilities
    from visionservex.registry import default_registry

    reg = default_registry()
    rows: list[dict] = []
    for e in reg.list():
        try:
            rows.append(model_capabilities(e.id))
        except Exception as exc:  # never let one model break the whole inventory
            rows.append({"model_id": e.id, "family": e.family, "task": e.task, "error": str(exc)})
    rows.sort(key=lambda r: (r.get("task", ""), r.get("family", ""), r.get("model_id", "")))
    return rows


def _yn(v) -> str:
    return "✅" if v else "—"


def write_inventory_md(rows: list[dict], path: Path) -> None:
    by_task: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_task[r.get("task", "?")].append(r)

    md = [
        "# VisionServeX v3.15.0 — Model Inventory",
        "",
        "_Auto-generated by `tools/qa/v315_model_inventory.py` (derived from "
        "registry + policy + capability tables + engine registry)._",
        "",
        f"**Total models:** {len(rows)}",
        "",
        "## Summary by task",
        "",
        "| Task | Families | Variants | Inference-ready | Train-ready | Export-ready | Catalog-only | Blocked |",
        "|---|--:|--:|--:|--:|--:|--:|--:|",
    ]
    for task in sorted(by_task):
        rs = by_task[task]
        fams = len({r.get("family") for r in rs})
        inf = sum(1 for r in rs if r.get("readiness") in ("inference-ready", "train-ready"))
        tr = sum(1 for r in rs if r.get("readiness") == "train-ready")
        exp = sum(1 for r in rs if r.get("export_supported"))
        cat = sum(1 for r in rs if r.get("readiness") == "catalog-only")
        blk = sum(1 for r in rs if r.get("readiness") == "blocked")
        md.append(f"| {task} | {fams} | {len(rs)} | {inf} | {tr} | {exp} | {cat} | {blk} |")

    for task in sorted(by_task):
        md += [
            "",
            f"## {task}",
            "",
            "| Model ID | Family | Engine | Readiness | Legal | Safe | Train | Reload-predict | Export | Blocker |",
            "|---|---|---|---|---|:--:|:--:|:--:|---|---|",
        ]
        for r in sorted(by_task[task], key=lambda r: (r.get("family", ""), r.get("model_id", ""))):
            md.append(
                f"| {r.get('model_id')} | {r.get('family')} | {r.get('engine')} | "
                f"{r.get('readiness')} | {r.get('legal_status')} | {_yn(r.get('commercial_safe'))} | "
                f"{_yn(r.get('train_supported'))} | {_yn(r.get('trained_checkpoint_predict_supported'))} | "
                f"{','.join(r.get('export_supported', [])) or '—'} | {(r.get('exact_blocker') or '')[:70]} |"
            )
    path.write_text("\n".join(md) + "\n")


def write_truth_table_md(rows: list[dict], path: Path) -> None:
    by_family: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_family[r.get("family", "?")].append(r)

    md = [
        "# VisionServeX v3.15.0 — Model Truth Table (all families)",
        "",
        "_Auto-generated by `tools/qa/v315_model_inventory.py`._",
        "",
        "| Family | Variants | Task | License | Pretrained inf. | Train | Reload-predict | Export | Default-safe | Blocker |",
        "|---|--:|---|---|:--:|:--:|:--:|---|:--:|---|",
    ]
    for fam in sorted(by_family):
        rs = by_family[fam]
        r0 = rs[0]
        n_inf = sum(1 for r in rs if r.get("pretrained_inference_supported"))
        n_train = sum(1 for r in rs if r.get("train_supported"))
        n_reload = sum(1 for r in rs if r.get("trained_checkpoint_predict_supported"))
        n_safe = sum(1 for r in rs if r.get("commercial_safe"))
        exports = sorted({x for r in rs for x in r.get("export_supported", [])})
        blockers = sorted({r.get("exact_blocker") for r in rs if r.get("exact_blocker")})
        md.append(
            f"| {fam} | {len(rs)} | {r0.get('task')} | {r0.get('license_code')} | "
            f"{n_inf}/{len(rs)} | {n_train}/{len(rs)} | {n_reload}/{len(rs)} | "
            f"{','.join(exports) or '—'} | {n_safe}/{len(rs)} | {(blockers[0] if blockers else '')[:50]} |"
        )
    path.write_text("\n".join(md) + "\n")


def main() -> None:
    rows = build_rows()
    outdir = Path("docs/qa/v315_model_coverage")
    outdir.mkdir(parents=True, exist_ok=True)
    (outdir / "model_inventory.json").write_text(json.dumps(rows, indent=2, default=str))
    write_inventory_md(rows, outdir / "model_inventory.md")
    write_truth_table_md(rows, outdir / "model_truth_table.md")

    from collections import Counter

    readiness = Counter(r.get("readiness") for r in rows)
    print(f"models: {len(rows)}")
    print("readiness:", dict(readiness))
    print("commercial_safe:", sum(1 for r in rows if r.get("commercial_safe")))
    print(
        "train-ready families:",
        sorted({r["family"] for r in rows if r.get("readiness") == "train-ready"}),
    )
    print(f"wrote {outdir}/model_inventory.json|.md and model_truth_table.md")


if __name__ == "__main__":
    main()
