#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Arash Sajjadi
"""v3.17.0: generate the data-driven model docs from the live registry/capabilities.

Writes (always current — derived from source):
    docs/model_matrix.md         (every model id, full lifecycle truth)
    docs/training_matrix.md      (train-ready models + dataset/API/reload/export)
    docs/legal_model_audit.md    (license / commercial-safety / gated audit)
"""

from __future__ import annotations

from collections import Counter, defaultdict
from pathlib import Path


def _yn(v) -> str:
    return "✅" if v else "—"


def _rows():
    from visionservex.core.model import model_capabilities
    from visionservex.registry import default_registry

    rows = [model_capabilities(e.id) for e in default_registry().list()]
    rows.sort(key=lambda r: (r["task"], r["family"], r["model_id"]))
    return rows


def gen_model_matrix(rows, path: Path) -> None:
    by_task = defaultdict(list)
    for r in rows:
        by_task[r["task"]].append(r)
    md = [
        "# VisionServeX Model Matrix",
        "",
        "_Auto-generated by `tools/qa/v317_generate_matrix_docs.py` from the live registry +"
        " `model_capabilities()`. Every registered model id appears here._",
        "",
        f"**Total models:** {len(rows)} — "
        + ", ".join(f"{k}: {v}" for k, v in sorted(Counter(r["readiness"] for r in rows).items())),
        "",
    ]
    for task in sorted(by_task):
        md += [
            f"## {task} ({len(by_task[task])})",
            "",
            "| Model ID | Family | License | Gated | Inference | Train | Reload | Predict-reload | Export | Readiness | Blocker |",
            "|---|---|---|:--:|:--:|:--:|:--:|:--:|---|---|---|",
        ]
        for r in by_task[task]:
            md.append(
                f"| {r['model_id']} | {r['family']} | {r['license_code']} | {_yn(r['gated'])} | "
                f"{_yn(r['pretrained_inference_supported'])} | {_yn(r['train_supported'])} | "
                f"{_yn(r['checkpoint_load_supported'])} | {_yn(r['trained_checkpoint_predict_supported'])} | "
                f"{','.join(r['export_supported']) or '—'} | {r['readiness']} | {r['exact_blocker'] or ''} |"
            )
        md.append("")
    path.write_text("\n".join(md) + "\n")


def gen_training_matrix(rows, path: Path) -> None:
    tr = [r for r in rows if r["readiness"] == "train-ready"]
    md = [
        "# VisionServeX Training Matrix",
        "",
        "_Train-ready models only (full lifecycle train→checkpoint→reload→predict→export)._",
        "",
        "| Model ID | Family | Dataset format | Reload API | Predict after reload | Export | Validated | Blocker |",
        "|---|---|---|---|:--:|---|:--:|---|",
    ]
    for r in tr:
        ds = ", ".join(r["supported_dataset_formats"]) or "—"
        md.append(
            f"| {r['model_id']} | {r['family']} | {ds} | "
            f"`VisionModel.from_checkpoint(ckpt, model_id=...)` | "
            f"{_yn(r['trained_checkpoint_predict_supported'])} | "
            f"{','.join(r['export_supported']) or '—'} | {_yn(r['validated_lifecycle'])} | {r['exact_blocker'] or '—'} |"
        )
    md += [
        "",
        f"**{len(tr)} train-ready models.** All other detectors/classifiers are inference-ready or "
        "blocked — see `docs/model_matrix.md` for the exact per-variant blocker.",
        "",
    ]
    path.write_text("\n".join(md) + "\n")


def gen_legal_audit(rows, path: Path) -> None:
    md = [
        "# VisionServeX Legal / Commercial-Safety Model Audit",
        "",
        "_Per-model license posture from the curated policy table + registry._",
        "",
        "## Summary",
        "",
        "| Legal status | Models |",
        "|---|--:|",
    ]
    for k, v in sorted(Counter(r["legal_status"] for r in rows).items()):
        md.append(f"| {k} | {v} |")
    md += [
        "",
        f"- **commercial-safe (curated policy default-safe):** {sum(1 for r in rows if r['commercial_safe'])}",
        f"- **gated (HF token required):** {sum(1 for r in rows if r['gated'])}",
        "- **Ultralytics / AGPL / GPL / SSPL runtime:** none (test-enforced).",
        "- **YOLO-NAS / Deci non-commercial training:** blocked.",
        "",
        "## Gated models (BYOT — token server-side only, never logged/committed)",
        "",
        "| Model ID | Family | License | Legal status |",
        "|---|---|---|---|",
    ]
    for r in rows:
        if r["gated"]:
            md.append(
                f"| {r['model_id']} | {r['family']} | {r['license_code']} | {r['legal_status']} |"
            )
    md += [
        "",
        "## Non-commercial / enterprise / review (NOT default-safe)",
        "",
        "| Model ID | Family | License | Legal status |",
        "|---|---|---|---|",
    ]
    for r in rows:
        if r["legal_status"] in (
            "noncommercial_restricted",
            "enterprise_license_required",
            "legal_review_required",
        ):
            md.append(
                f"| {r['model_id']} | {r['family']} | {r['license_code']} | {r['legal_status']} |"
            )
    path.write_text("\n".join(md) + "\n")


def main() -> None:
    rows = _rows()
    docs = Path("docs")
    docs.mkdir(exist_ok=True)
    gen_model_matrix(rows, docs / "model_matrix.md")
    gen_training_matrix(rows, docs / "training_matrix.md")
    gen_legal_audit(rows, docs / "legal_model_audit.md")
    print(
        f"generated model_matrix.md / training_matrix.md / legal_model_audit.md from {len(rows)} models"
    )


if __name__ == "__main__":
    main()
