#!/usr/bin/env python
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Arash Sajjadi
"""v3.17.0 QA: discover the FULL VisionServeX model catalog from the real registry.

Programmatic — never from memory. Every registered model id becomes a row (even
blocked/catalog-only), with its capability-truth claim and the exact source.

    python tools/qa/v317_discover_model_catalog.py
    -> docs/qa/v317_full_model_matrix/discovered_models.json
    -> docs/qa/v317_full_model_matrix/discovered_models.md
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path


def _variant(model_id: str, family: str) -> str:
    pref = f"{family}-"
    return model_id[len(pref) :] if model_id.startswith(pref) else model_id


def discover() -> list[dict]:
    from visionservex.core.model import model_capabilities
    from visionservex.registry import default_registry

    reg = default_registry()
    rows: list[dict] = []
    for e in reg.list():
        cap = model_capabilities(e.id)
        rows.append(
            {
                "model_id": e.id,
                "family": e.family,
                "variant": _variant(e.id, e.family),
                "task": e.task,
                "source": "registry:models.yaml",
                "license": e.license,
                "gated": bool(cap["gated"]),
                "requires_hf_token": bool(e.requires_auth),
                "dependencies": [e.install_extra] if e.install_extra else [],
                "claimed_readiness": cap["readiness"],
                "claimed_train_supported": cap["train_supported"],
                "claimed_inference_supported": cap["pretrained_inference_supported"],
                "claimed_export_supported": cap["export_supported"],
                "commercial_safe": cap["commercial_safe"],
                "exact_blocker": cap["exact_blocker"],
                "exact_claim_source": f"registry id={e.id} (implementation_status={e.implementation_status})",
            }
        )
    rows.sort(key=lambda r: (r["task"], r["family"], r["model_id"]))
    return rows


def write_md(rows: list[dict], path: Path) -> None:
    by_task: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        by_task[r["task"]].append(r)
    md = [
        "# VisionServeX v3.17.0 — Discovered Model Catalog",
        "",
        "_Auto-generated by `tools/qa/v317_discover_model_catalog.py` from the live registry._",
        "",
        f"**Total discovered models:** {len(rows)}",
        "",
        "| Task | Variants |",
        "|---|--:|",
    ]
    for task in sorted(by_task):
        md.append(f"| {task} | {len(by_task[task])} |")
    for task in sorted(by_task):
        md += [
            "",
            f"## {task} ({len(by_task[task])})",
            "",
            "| Model ID | Family | License | Gated | Readiness | Train | Inference | Export | Blocker |",
            "|---|---|---|:--:|---|:--:|:--:|---|---|",
        ]
        for r in by_task[task]:
            md.append(
                f"| {r['model_id']} | {r['family']} | {r['license']} | "
                f"{'🔒' if r['gated'] else '—'} | {r['claimed_readiness']} | "
                f"{'✅' if r['claimed_train_supported'] else '—'} | "
                f"{'✅' if r['claimed_inference_supported'] else '—'} | "
                f"{','.join(r['claimed_export_supported']) or '—'} | {r['exact_blocker'] or ''} |"
            )
    path.write_text("\n".join(md) + "\n")


def main() -> None:
    rows = discover()
    out = Path("docs/qa/v317_full_model_matrix")
    out.mkdir(parents=True, exist_ok=True)
    (out / "discovered_models.json").write_text(json.dumps(rows, indent=2, default=str))
    write_md(rows, out / "discovered_models.md")
    print(f"discovered {len(rows)} models")
    print("by task:", dict(Counter(r["task"] for r in rows)))
    print("by readiness:", dict(Counter(r["claimed_readiness"] for r in rows)))
    print("gated:", sum(1 for r in rows if r["gated"]))
    print(f"wrote {out}/discovered_models.json|.md")


if __name__ == "__main__":
    main()
