# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Arash Sajjadi
"""v3.19 RF-DETR live train-lifecycle matrix — the REAL native trainer.

RF-DETR trains through its own package's PyTorch-Lightning stack (not a
VisionServeX wrapper), so v3.18 honestly kept the 8 derived variants
``TRAIN_READY_DERIVED``. This tool runs that native lifecycle for real on a tiny
synthetic COCO smoke dataset (generated by ``rfdetr.datasets.synthetic``):

    generate COCO -> RFDETR<Variant>().train(...) -> checkpoint .pth ->
    VisionModel.from_checkpoint(...) -> predict/segment-after-reload ->
    valid schema -> ONNX export

A variant is promoted to ``TRAIN_READY_LIVE`` only when every stage passes.
Anything that OOMs / is too slow / crashes upstream gets an EXACT blocker, never
a fake skip.

Resource safety (machine froze once on VRAM saturation — AGENT_RULES.md):
* one variant per subprocess, strictly serial, VRAM-guarded before each spawn;
* GPU preferred (DETR training on CPU is impractical), small batch, 1 epoch,
  tiny dataset; subprocess exit frees all VRAM before the next variant.

Usage::

    python tools/qa/v319_rfdetr_live_train_matrix.py            # driver
    python tools/qa/v319_rfdetr_live_train_matrix.py --worker rfdetr-nano --device cuda
"""

from __future__ import annotations

import argparse
import contextlib
import json
import os

# RF-DETR's segmentation mask loss is a ``torch.jit.script`` kernel that triggers
# runtime nvrtc compilation; on a torch+cu130 build missing
# ``libnvrtc-builtins.so.13.0`` that JIT path fails. Disabling the JIT compiler
# (eager fallback) sidesteps it without changing results. Must be set before
# torch is imported in the worker.
os.environ.setdefault("PYTORCH_JIT", "0")

import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT_DIR = REPO / "docs" / "qa" / "v319_operationalize_all_models"
JSONL = OUT_DIR / "rfdetr_live_train_matrix.jsonl"
JSON_OUT = OUT_DIR / "rfdetr_live_train_matrix.json"
MD_OUT = OUT_DIR / "rfdetr_live_train_matrix.md"

VARIANTS = [
    "rfdetr-nano",
    "rfdetr-small",
    "rfdetr-medium",
    "rfdetr-base",
    "rfdetr-large",
    "rfdetr-seg-nano",
    "rfdetr-seg-small",
    "rfdetr-seg-medium",
]
PER_MODEL_TIMEOUT_S = 900
DRIVER_WALLCLOCK_BUDGET_S = 540
MIN_FREE_VRAM_GB = 6.0


def _free_vram_gb() -> float:
    try:
        import torch

        if not torch.cuda.is_available():
            return 0.0
        free, _ = torch.cuda.mem_get_info()
        return free / 1024**3
    except Exception:
        return 0.0


# --------------------------------------------------------------------------- #
# Worker — full native lifecycle for ONE variant.
# --------------------------------------------------------------------------- #
def run_one(model_id: str, device: str) -> dict:
    t0 = time.perf_counter()
    is_seg = model_id.startswith("rfdetr-seg")
    row = {
        "model_id": model_id,
        "task": "segment" if is_seg else "detect",
        "device": device,
        "dataset_built": False,
        "train": False,
        "checkpoint_exists": False,
        "checkpoint_metadata_ok": False,
        "reload": False,
        "predict_after_reload": False,
        "output_schema_valid": False,
        "export_supported": False,
        "export": False,
        "status": "FAIL",
        "final_state": "FAIL",
        "live_verified": False,
        "latency_ms": 0.0,
        "peak_vram_mb": 0.0,
        "error_type": None,
        "error_message": None,
        "blocker": None,
    }
    workdir = Path(tempfile.mkdtemp(prefix=f"v319_rfdetr_{model_id}_"))
    try:
        import torch
        from rfdetr.datasets.synthetic import generate_coco_dataset

        from visionservex import VisionModel
        from visionservex.core.model import model_capabilities
        from visionservex.core.results import BaseResult
        from visionservex.engines.rfdetr import _ALL_CLASSES, _load_rfdetr_class

        row["export_supported"] = bool(model_capabilities(model_id).get("export_supported"))

        # ---- 1. build model + read its native resolution ----
        # The training dataloader feeds images at the dataset's img_size, and each
        # variant's backbone requires that size be divisible by a variant-specific
        # block (e.g. 56 for base, 12/24 for seg). The model's own native
        # resolution is guaranteed compatible, so we generate the dataset at it.
        cls = _load_rfdetr_class(_ALL_CLASSES[model_id])
        out = workdir / "run"
        model = cls(device=device)
        cfg = getattr(model, "model_config", None)
        res = int(getattr(cfg, "resolution", 0) or getattr(model, "resolution", 0) or 512)
        row["resolution"] = res

        # ---- 2. tiny synthetic COCO at the model's native resolution ----
        ds = workdir / "coco"
        generate_coco_dataset(
            output_dir=str(ds),
            num_images=24,
            img_size=res,
            class_mode="shape",
            min_objects=1,
            max_objects=3,
            with_segmentation=is_seg,
        )
        # The synthetic generator writes a ``val/`` split, but the rfdetr COCO
        # loader looks for ``valid/`` — bridge the naming.
        if (ds / "val").exists() and not (ds / "valid").exists():
            shutil.move(str(ds / "val"), str(ds / "valid"))
        row["dataset_built"] = (ds / "train" / "_annotations.coco.json").exists() and (
            ds / "valid" / "_annotations.coco.json"
        ).exists()

        # ---- 3. native train ----
        model.train(
            dataset_dir=str(ds),
            output_dir=str(out),
            epochs=1,
            batch_size=2,
            grad_accum_steps=1,
            num_workers=0,
            lr=1e-4,
            warmup_epochs=0,
            checkpoint_interval=1,
            early_stopping=False,
            tensorboard=False,
            wandb=False,
            progress_bar=False,
            run_test=False,
            device=device if device.startswith("cuda") else "cpu",
        )
        row["train"] = True
        if torch.cuda.is_available():
            row["peak_vram_mb"] = round(torch.cuda.max_memory_allocated() / 1024**2, 1)

        # ---- 3. locate checkpoint ----
        ckpts = sorted(out.rglob("*.pth")) + sorted(out.rglob("*.ckpt"))
        best = [p for p in ckpts if "best" in p.name.lower()]
        ckpt = (best[0] if best else ckpts[0]) if ckpts else None
        row["checkpoint_exists"] = ckpt is not None
        if ckpt is None:
            row["error_type"] = "NoCheckpoint"
            row["error_message"] = f"train wrote no .pth/.ckpt under {out}"
            row["blocker"] = "UPSTREAM_TRAINER_FAILURE"
            return row

        # ---- 4. checkpoint metadata ----
        with contextlib.suppress(Exception):
            blob = torch.load(str(ckpt), map_location="cpu", weights_only=False)
            md = blob if isinstance(blob, dict) else {}
            row["checkpoint_metadata_ok"] = bool(
                md.get("args") or md.get("model") or md.get("state_dict") or md.get("class_names")
            )

        # free the trainer's GPU memory before reloading
        del model
        with contextlib.suppress(Exception):
            torch.cuda.empty_cache()

        # ---- 5. reload via the public from_checkpoint API ----
        reload_dev = device if device.startswith("cuda") else "cpu"
        trained = VisionModel.from_checkpoint(str(ckpt), model_id=model_id, device=reload_dev)
        row["reload"] = True

        # ---- 6. predict / segment after reload ----
        from PIL import Image, ImageDraw

        img = Image.new("RGB", (512, 512), (180, 200, 220))
        d = ImageDraw.Draw(img)
        d.rectangle([60, 60, 220, 300], fill=(200, 60, 60))
        d.ellipse([260, 180, 420, 360], fill=(60, 120, 200))
        result = trained.predict(img, threshold=0.0)  # threshold 0 so the smoke surfaces boxes
        row["predict_after_reload"] = True
        row["output_schema_valid"] = isinstance(result, BaseResult)

        # ---- 7. export ----
        if row["export_supported"]:
            try:
                onnx = workdir / "model.onnx"
                trained.export("onnx", onnx)
                row["export"] = onnx.exists() and onnx.stat().st_size > 0
            except Exception as e:
                row["export"] = False
                row["error_message"] = f"export warn: {str(e)[:200]}"
        else:
            row["export"] = True

        core_ok = (
            row["train"]
            and row["checkpoint_exists"]
            and row["reload"]
            and row["predict_after_reload"]
            and row["output_schema_valid"]
        )
        export_ok = (not row["export_supported"]) or row["export"]
        if core_ok and export_ok:
            row["status"] = "PASS"
            row["final_state"] = "TRAIN_READY_LIVE"
            row["live_verified"] = True
        else:
            row["status"] = "FAIL"
            row["final_state"] = (
                "EXPORT_FAILURE" if not export_ok else "VARIANT_NOT_LIFECYCLE_VALIDATED"
            )
            row["blocker"] = row["final_state"]
        with contextlib.suppress(Exception):
            trained.unload()
    except Exception as e:
        import traceback

        msg = str(e)
        low = (msg + type(e).__name__).lower()
        row["error_type"] = type(e).__name__
        row["error_message"] = msg[:700]
        if "out of memory" in low or "cuda out of memory" in low:
            row["blocker"] = "OOM_BLOCKED"
        elif "_annotations.coco" in low or ("dataset" in low and "format" in low):
            row["blocker"] = "DATASET_FORMAT_FAILURE"
        else:
            row["blocker"] = "UPSTREAM_TRAINER_FAILURE"
        row["final_state"] = row["blocker"]
        row["status"] = "FAIL" if row["blocker"] != "OOM_BLOCKED" else "SKIP_BLOCKED"
        sys.stderr.write(traceback.format_exc()[-2000:])
    finally:
        row["latency_ms"] = round((time.perf_counter() - t0) * 1000.0, 1)
        shutil.rmtree(workdir, ignore_errors=True)
    return row


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #
def load_done() -> dict[str, dict]:
    done = {}
    if JSONL.exists():
        for line in JSONL.read_text().splitlines():
            if line.strip():
                with contextlib.suppress(Exception):
                    r = json.loads(line)
                    done[r["model_id"]] = r
    return done


def write_outputs(rows: list[dict]) -> None:
    order = {m: i for i, m in enumerate(VARIANTS)}
    rows = sorted(rows, key=lambda r: order.get(r["model_id"], 99))
    summary = {"PASS": 0, "FAIL": 0, "SKIP_BLOCKED": 0}
    for r in rows:
        summary[r.get("status", "FAIL")] = summary.get(r.get("status", "FAIL"), 0) + 1
    JSON_OUT.write_text(
        json.dumps(
            {
                "schema": "v319_rfdetr_live_train_matrix",
                "n": len(rows),
                "summary": summary,
                "results": rows,
            },
            indent=2,
        )
    )

    def y(b):
        return "yes" if b else "—"

    lines = [
        "# v3.19 RF-DETR Live Train-Lifecycle Matrix",
        "",
        "Real native RF-DETR training (PyTorch-Lightning) on a tiny synthetic COCO smoke.",
        f"**{summary.get('PASS', 0)} PASS · {summary.get('FAIL', 0)} FAIL · "
        f"{summary.get('SKIP_BLOCKED', 0)} SKIP_BLOCKED**",
        "",
        "| Model | Task | Train | Ckpt | Reload | Predict | Schema | Export | VRAM MB | Final | Status |",
        "|---|---|:-:|:-:|:-:|:-:|:-:|:-:|--:|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| `{r['model_id']}` | {r.get('task', '')} | {y(r.get('train'))} | "
            f"{y(r.get('checkpoint_exists'))} | {y(r.get('reload'))} | {y(r.get('predict_after_reload'))} | "
            f"{y(r.get('output_schema_valid'))} | {y(r.get('export')) if r.get('export_supported') else 'n/a'} | "
            f"{r.get('peak_vram_mb', 0)} | {r.get('final_state', '')} | {r.get('status', '')} |"
        )
    MD_OUT.write_text("\n".join(lines) + "\n")


def drive(device: str) -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    done = load_done()
    todo = [m for m in VARIANTS if m not in done]
    print(f"[driver] variants={len(VARIANTS)} done={len(done)} todo={len(todo)} device={device}")
    start = time.perf_counter()
    env = dict(os.environ)
    env["TMPDIR"] = os.environ.get("TMPDIR", "/home/arash/.cache/vsx_tmp")
    processed = 0
    with JSONL.open("a") as fh:
        for m in todo:
            if time.perf_counter() - start > DRIVER_WALLCLOCK_BUDGET_S:
                print(f"[driver] budget hit; {len(todo) - processed} remain. Re-run.")
                break
            free = _free_vram_gb()
            use_dev = device
            if device.startswith("cuda") and free < MIN_FREE_VRAM_GB:
                row = {
                    "model_id": m,
                    "task": "segment" if "seg" in m else "detect",
                    "status": "SKIP_BLOCKED",
                    "final_state": "GPU_REQUIRED_FOR_LIVE_TRAIN",
                    "blocker": "GPU_REQUIRED_FOR_LIVE_TRAIN",
                    "error_message": f"only {free:.1f} GB VRAM free (< {MIN_FREE_VRAM_GB})",
                    "latency_ms": 0.0,
                }
            else:
                t0 = time.perf_counter()
                cmd = [sys.executable, __file__, "--worker", m, "--device", use_dev]
                try:
                    proc = subprocess.run(
                        cmd, capture_output=True, text=True, timeout=PER_MODEL_TIMEOUT_S, env=env
                    )
                    line = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else ""
                    row = (
                        json.loads(line)
                        if line.startswith("{")
                        else {
                            "model_id": m,
                            "status": "FAIL",
                            "final_state": "UPSTREAM_TRAINER_FAILURE",
                            "blocker": "UPSTREAM_TRAINER_FAILURE",
                            "error_type": "WorkerCrash",
                            "error_message": (proc.stderr or "no output")[-400:],
                            "latency_ms": round((time.perf_counter() - t0) * 1000, 1),
                        }
                    )
                except subprocess.TimeoutExpired:
                    row = {
                        "model_id": m,
                        "status": "SKIP_BLOCKED",
                        "final_state": "CPU_TRAIN_TOO_HEAVY"
                        if not use_dev.startswith("cuda")
                        else "TRAIN_TIMEOUT",
                        "blocker": "CPU_TRAIN_TOO_HEAVY"
                        if not use_dev.startswith("cuda")
                        else "TRAIN_TIMEOUT",
                        "error_message": f"exceeded {PER_MODEL_TIMEOUT_S}s",
                        "latency_ms": PER_MODEL_TIMEOUT_S * 1000.0,
                    }
            fh.write(json.dumps(row) + "\n")
            fh.flush()
            processed += 1
            print(
                f"[{processed}/{len(todo)}] {row.get('status'):<12} {m} -> {row.get('final_state')} "
                f"({row.get('latency_ms')}ms, {row.get('peak_vram_mb', 0)}MB)"
            )

    rows = list(load_done().values())
    write_outputs(rows)
    remaining = len([m for m in VARIANTS if m not in load_done()])
    print("[driver] ALL DONE" if remaining == 0 else f"[driver] {remaining} remaining — re-run.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--worker", default=None)
    ap.add_argument("--device", default="cuda")
    args = ap.parse_args()
    if args.worker:
        print(json.dumps(run_one(args.worker, args.device)))
        return 0
    return drive(args.device)


if __name__ == "__main__":
    raise SystemExit(main())
