"""Cloudflare Tunnel integration.

The ``cloudflared`` daemon is an external binary; VisionServeX does not vendor
it. We provide:

* a doctor that detects the binary and tells you how to install it;
* a safe ingress config generator with a catch-all 404 rule;
* a checklist that must be acknowledged before going public.
"""

from __future__ import annotations

import platform
import shutil
import subprocess
from textwrap import dedent

import yaml

from visionservex.config import get_settings


class CloudflaredNotFound(RuntimeError):
    pass


def cloudflared_install_hint() -> str:
    system = platform.system().lower()
    if system == "linux":
        return (
            "Install on Linux:\n"
            "  Debian/Ubuntu:  curl -L https://pkg.cloudflare.com/cloudflared-stable-linux-amd64.deb -o /tmp/cf.deb && sudo dpkg -i /tmp/cf.deb\n"
            "  RHEL/Fedora:    sudo rpm -ivh https://pkg.cloudflare.com/cloudflared-stable-linux-amd64.rpm\n"
            "  Tarball:        https://github.com/cloudflare/cloudflared/releases (download, chmod +x, move to PATH)"
        )
    if system == "darwin":
        return "Install on macOS: brew install cloudflare/cloudflare/cloudflared"
    if system == "windows":
        return (
            "Install on Windows (PowerShell):\n"
            "  winget install --id Cloudflare.cloudflared\n"
            "Or download from https://github.com/cloudflare/cloudflared/releases and add to PATH."
        )
    return "See https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"


def cloudflared_doctor() -> dict:
    path = shutil.which("cloudflared")
    if path is None:
        return {
            "installed": False,
            "path": None,
            "version": None,
            "install_hint": cloudflared_install_hint(),
        }
    version = "unknown"
    try:
        out = subprocess.run(
            ["cloudflared", "--version"],
            check=False,
            capture_output=True,
            text=True,
            timeout=10,
        )
        version = (out.stdout or out.stderr).strip().splitlines()[0]
    except Exception:  # pragma: no cover - defensive
        pass
    return {
        "installed": True,
        "path": path,
        "version": version,
        "install_hint": "",
    }


def generate_config(*, tunnel_name: str, hostname: str) -> str:
    """Generate a safe cloudflared ingress YAML.

    The config:
    * sends ``hostname`` to ``http://127.0.0.1:<port>`` (the local origin),
    * adds a catch-all 404 rule so unrelated hostnames cannot reach the API,
    * does NOT include credentials inline (set ``TUNNEL_TOKEN`` env or use the
      credentials file written by ``cloudflared tunnel create``).
    """
    settings = get_settings()
    port = settings.server.port

    credentials_hint = f"~/.cloudflared/<TUNNEL_UUID>.json (set automatically by `cloudflared tunnel create {tunnel_name}`)"
    payload = {
        "tunnel": tunnel_name,
        "credentials-file": credentials_hint,
        "ingress": [
            {
                "hostname": hostname,
                "service": f"http://127.0.0.1:{port}",
                "originRequest": {
                    "connectTimeout": "10s",
                    "tlsTimeout": "10s",
                    "noTLSVerify": False,
                    "httpHostHeader": hostname,
                },
            },
            {"service": "http_status:404"},
        ],
    }
    yaml_body = yaml.safe_dump(payload, sort_keys=False)

    banner = dedent(
        f"""\
        # Generated by VisionServeX. Review before use.
        #
        # Before running this tunnel:
        #   1. Set VISIONSERVEX_AUTH__ENABLED=true and VISIONSERVEX_AUTH__API_KEY=<strong secret>.
        #   2. Verify the origin (127.0.0.1:{port}) is not also exposed directly to the internet.
        #   3. Configure Cloudflare Access policies in the Zero Trust dashboard:
        #        * Email/identity provider for browser-driven access.
        #        * Service tokens for programmatic clients (CF-Access-Client-Id / -Secret).
        #        * Optional mTLS for high-value clients.
        #   4. Replace `credentials-file` above with the path written by `cloudflared tunnel create`.
        #
        # The catch-all `http_status:404` rule below MUST stay present so unrelated
        # hostnames cannot reach the API through this tunnel.
        """
    )
    return banner + yaml_body


def public_checklist(*, auth_enabled: bool) -> list[str]:
    base = [
        "VISIONSERVEX_AUTH__ENABLED=true",
        "VISIONSERVEX_AUTH__API_KEY is a high-entropy random string (≥32 bytes)",
        "Origin port is not exposed directly to the public internet (firewalled).",
        "Cloudflare Access policy attached to the hostname (identity, service tokens, or mTLS).",
        "Rate limit and max upload size tuned for your hardware/tier.",
        "Audit logging enabled and shipped to a secure store.",
        "Upstream model and checkpoint licenses reviewed for your deployment.",
    ]
    if not auth_enabled:
        base.insert(0, "AUTH IS CURRENTLY DISABLED — enable it before running the tunnel.")
    return base


__all__ = [
    "CloudflaredNotFound",
    "cloudflared_doctor",
    "cloudflared_install_hint",
    "generate_config",
    "public_checklist",
]
