# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Arash Sajjadi
"""v2.42.0: provenance tracking for generated final-report artifacts.

Every generated file (model_coverage_ledger.csv/json, final_winners.json,
notebook_model_call_ledger.json) must be accompanied by a
``<file>.provenance.json`` sidecar that proves:

1. The file was generated by the reconciler, not manually edited.
2. The file was generated in the current run (by matching run_id).
3. The SHA-256 hash of the file at write time still matches.
4. Required columns are present (hard schema enforcement).
5. Row count matches the expected registry model count.

If any of these fail, ``verify_generated_artifacts`` raises with
``MANUAL_EDIT_DETECTED`` or ``STALE_ARTIFACT_DETECTED``.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import time
from pathlib import Path
from typing import Any

REQUIRED_LEDGER_COLUMNS: frozenset[str] = frozenset(
    {
        "model_id",
        "family",
        "task",
        "final_state",
        "blocker_code",
        "called_in_current_notebook_run",
        "current_run_artifact_exists",
        "evidence_source_kind",
        "current_run_id",
        "attempted_command",
        "evidence_artifact",
        "called_in_notebook",
        "registry_status",
        "execution_status",
    }
)

OLD_11_COLUMN_SCHEMA: frozenset[str] = frozenset(
    {
        "model_id",
        "family",
        "task",
        "engine",
        "license_status",
        "default_safe",
        "install_extra",
        "implementation_status",
        "final_state",
        "blocker_code",
        "run_mode",
    }
)


def _sha256(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _git_commit() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "--short", "HEAD"], text=True).strip()
    except Exception:
        return "unknown"


def _vsx_version() -> str:
    try:
        import importlib.metadata

        return importlib.metadata.version("visionservex")
    except Exception:
        return "unknown"


def write_provenance(
    artifact_path: Path,
    *,
    run_id: str,
    source_artifacts: list[str] | None = None,
    extra: dict[str, Any] | None = None,
) -> Path:
    """Write a provenance sidecar for ``artifact_path``.

    Returns the path of the sidecar file.
    """
    prov_path = artifact_path.with_suffix(artifact_path.suffix + ".provenance.json")
    prov: dict[str, Any] = {
        "generated_by": "visionservex.reporting.v239_reconciler.write_outputs",
        "generator_version": "v2.42.0",
        "visionservex_version": _vsx_version(),
        "git_commit": _git_commit(),
        "run_id": run_id,
        "generated_at_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "artifact_path": str(artifact_path.resolve()),
        "artifact_sha256": _sha256(artifact_path) if artifact_path.exists() else "",
        "source_artifacts": source_artifacts or [],
        "manual_edit_detected": False,
    }
    if extra:
        prov.update(extra)
    prov_path.write_text(json.dumps(prov, indent=2))
    return prov_path


def verify_artifact(
    artifact_path: Path,
    *,
    run_id: str,
    min_rows: int = 140,
) -> dict[str, Any]:
    """Verify a single generated artifact. Returns a result dict.

    Keys:
        ok, issues, row_count, column_count, required_columns_present,
        old_schema_detected, current_run_match, hash_match,
        manual_edit_detected, provenance_path, run_id_in_file.
    """
    result: dict[str, Any] = {
        "artifact_path": str(artifact_path),
        "ok": False,
        "issues": [],
        "row_count": 0,
        "column_count": 0,
        "required_columns_present": False,
        "old_schema_detected": False,
        "current_run_match": False,
        "hash_match": False,
        "manual_edit_detected": False,
        "provenance_path": "",
        "run_id_in_file": "",
    }

    if not artifact_path.exists():
        result["issues"].append(f"ARTIFACT_MISSING: {artifact_path}")
        return result

    prov_path = artifact_path.with_suffix(artifact_path.suffix + ".provenance.json")
    result["provenance_path"] = str(prov_path)

    prov: dict[str, Any] = {}
    if prov_path.exists():
        try:
            prov = json.loads(prov_path.read_text())
        except Exception as e:
            result["issues"].append(f"PROVENANCE_PARSE_ERROR: {e}")
    else:
        result["issues"].append("PROVENANCE_MISSING")

    # Hash check
    if prov.get("artifact_sha256"):
        current_hash = _sha256(artifact_path)
        result["hash_match"] = current_hash == prov["artifact_sha256"]
        if not result["hash_match"]:
            result["manual_edit_detected"] = True
            result["issues"].append(
                f"HASH_MISMATCH: expected {prov['artifact_sha256'][:12]}… got {current_hash[:12]}…"
            )
    else:
        result["issues"].append("PROVENANCE_HASH_MISSING")

    # Run ID match
    prov_run = prov.get("run_id", "")
    result["current_run_match"] = prov_run == run_id

    # Schema validation for CSV
    if artifact_path.suffix == ".csv":
        import csv as _csv

        try:
            rows = list(_csv.DictReader(artifact_path.open()))
        except Exception as e:
            result["issues"].append(f"CSV_PARSE_ERROR: {e}")
            return result
        cols = set(rows[0].keys()) if rows else set()
        result["row_count"] = len(rows)
        result["column_count"] = len(cols)

        if cols == OLD_11_COLUMN_SCHEMA:
            result["old_schema_detected"] = True
            result["issues"].append("OLD_11_COLUMN_SCHEMA_DETECTED")

        missing = REQUIRED_LEDGER_COLUMNS - cols
        result["required_columns_present"] = not missing
        if missing:
            result["issues"].append(f"MISSING_COLUMNS: {sorted(missing)}")

        if len(rows) < min_rows:
            result["issues"].append(f"ROW_COUNT_TOO_LOW: {len(rows)} < {min_rows}")

        # Extract run_id from first data row
        if rows and "current_run_id" in rows[0]:
            result["run_id_in_file"] = rows[0]["current_run_id"]

    # JSON schema check
    elif artifact_path.suffix == ".json":
        try:
            data = json.loads(artifact_path.read_text())
        except Exception as e:
            result["issues"].append(f"JSON_PARSE_ERROR: {e}")
            return result
        if isinstance(data, dict) and "rows" in data:
            result["row_count"] = len(data["rows"])
            result["run_id_in_file"] = data.get("run_id", "")
            if data.get("rows"):
                cols = set(data["rows"][0].keys())
                result["column_count"] = len(cols)
                missing = REQUIRED_LEDGER_COLUMNS - cols
                result["required_columns_present"] = not missing
                if missing:
                    result["issues"].append(f"MISSING_JSON_COLUMNS: {sorted(missing)}")
        elif isinstance(data, dict):
            result["row_count"] = 1

    result["ok"] = len(result["issues"]) == 0
    return result


def verify_generated_artifacts(
    root: Path,
    *,
    run_id: str,
    min_rows: int = 140,
    fail_on_manual_edit: bool = True,
    fail_on_stale: bool = True,
) -> dict[str, Any]:
    """Scan ``root`` for final report files and verify each one."""
    targets = [
        root / "model_coverage_ledger.csv",
        root / "model_coverage_ledger.json",
        root / "final_winners.json",
        root / "notebook_model_call_ledger.json",
    ]
    all_results: list[dict[str, Any]] = []
    any_fail = False

    for t in targets:
        if not t.exists():
            all_results.append(
                {
                    "artifact_path": str(t),
                    "ok": False,
                    "issues": ["ARTIFACT_MISSING"],
                }
            )
            any_fail = True
            continue
        res = verify_artifact(t, run_id=run_id, min_rows=min_rows)
        all_results.append(res)
        if not res["ok"]:
            any_fail = True

    payload: dict[str, Any] = {
        "status": "ok" if not any_fail else "failed",
        "run_id": run_id,
        "artifacts_checked": len(targets),
        "artifacts_ok": sum(1 for r in all_results if r.get("ok")),
        "artifacts_failed": sum(1 for r in all_results if not r.get("ok")),
        "results": all_results,
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    }
    return payload


__all__ = [
    "OLD_11_COLUMN_SCHEMA",
    "REQUIRED_LEDGER_COLUMNS",
    "verify_artifact",
    "verify_generated_artifacts",
    "write_provenance",
]
